name: Workflow Logs Cleaner

on:
  schedule:
    # Runs at 01:01 UTC on the 2nd of every month
    - cron: '1 1 2 * *'
  workflow_dispatch:
    inputs:
      runs_older_than:
        description: "Last X Days' Logs To Keep"
        default: "12"
        required: false
env:
  SCHEDULED_RUNS_OLDER_THAN: "12"

jobs:
  clean-logs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: igorjs/gh-actions-clean-workflow@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          runs_older_than: ${{ github.event.inputs.runs_older_than || env.SCHEDULED_RUNS_OLDER_THAN }} # optional
